I, [2020-03-23T14:40:14.317324 #4269]  INFO -- default-ubuntu-1804-2019-2-py3: -----> Cleaning up any prior instances of <default-ubuntu-1804-2019-2-py3>
I, [2020-03-23T14:40:14.317635 #4269]  INFO -- default-ubuntu-1804-2019-2-py3: -----> Destroying <default-ubuntu-1804-2019-2-py3>...
I, [2020-03-23T14:40:14.318337 #4269]  INFO -- default-ubuntu-1804-2019-2-py3: Finished destroying <default-ubuntu-1804-2019-2-py3> (0m0.00s).
I, [2020-03-23T14:40:14.318635 #4269]  INFO -- default-ubuntu-1804-2019-2-py3: -----> Testing <default-ubuntu-1804-2019-2-py3>
I, [2020-03-23T14:40:14.318760 #4269]  INFO -- default-ubuntu-1804-2019-2-py3: -----> Creating <default-ubuntu-1804-2019-2-py3>...
E, [2020-03-23T14:40:18.188347 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: Create failed on instance <default-ubuntu-1804-2019-2-py3>.
E, [2020-03-23T14:40:18.188494 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: ------Exception-------
E, [2020-03-23T14:40:18.188515 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: Class: Kitchen::ShellOut::ShellCommandFailed
E, [2020-03-23T14:40:18.188531 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: Message: Expected process to exit with [0], but received '100'
---- Begin output of docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20200323-4269-14oanc6 . ----
STDOUT: Sending build context to Docker daemon  986.1kB
Step 1/17 : FROM netmanagers/salt-2019.2-py3:ubuntu-18.04
 ---> 8b369f265be0
Step 2/17 : RUN [ ! -f "/sbin/initctl" ] || dpkg-divert --local --rename --add /sbin/initctl && ln -sf /bin/true /sbin/initctl
 ---> Using cache
 ---> d9831ce9b16b
Step 3/17 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 4f70242ef591
Step 4/17 : ENV container docker
 ---> Using cache
 ---> 54d68abaae2f
Step 5/17 : RUN apt-get update
 ---> Running in 4980e59b2d07
Get:1 https://repo.saltstack.com/py3/ubuntu/18.04/amd64/2019.2 bionic InRelease [2126 B]
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:3 https://repo.saltstack.com/py3/ubuntu/18.04/amd64/2019.2 bionic/main amd64 Packages [4398 B]
Get:4 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Reading package lists...
[91mE: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 10d 22h 56min 45s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 11d 0h 31min 42s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 10d 22h 59min 16s). Updates for this repository will not be applied.
[0m
STDERR: The command '/bin/sh -c apt-get update' returned a non-zero code: 100
---- End output of docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20200323-4269-14oanc6 . ----
Ran docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20200323-4269-14oanc6 . returned 100
E, [2020-03-23T14:40:18.188551 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: ----------------------
E, [2020-03-23T14:40:18.188567 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: ------Backtrace-------
E, [2020-03-23T14:40:18.188582 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/shell_out.rb:71:in `rescue in run_command'
E, [2020-03-23T14:40:18.188598 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/shell_out.rb:59:in `run_command'
E, [2020-03-23T14:40:18.188620 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/kitchen-docker-2.10.0/lib/kitchen/docker/helpers/cli_helper.rb:36:in `docker_command'
E, [2020-03-23T14:40:18.188637 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/kitchen-docker-2.10.0/lib/kitchen/docker/helpers/image_helper.rb:52:in `build_image'
E, [2020-03-23T14:40:18.188653 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/kitchen-docker-2.10.0/lib/kitchen/docker/container/linux.rb:38:in `create'
E, [2020-03-23T14:40:18.188671 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/kitchen-docker-2.10.0/lib/kitchen/driver/docker.rb:123:in `create'
E, [2020-03-23T14:40:18.188688 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:485:in `public_send'
E, [2020-03-23T14:40:18.188704 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:485:in `block in perform_action'
E, [2020-03-23T14:40:18.188719 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:552:in `synchronize_or_call'
E, [2020-03-23T14:40:18.188735 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:514:in `block in action'
E, [2020-03-23T14:40:18.188751 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2020-03-23T14:40:18.188767 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:513:in `action'
E, [2020-03-23T14:40:18.188782 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:485:in `perform_action'
E, [2020-03-23T14:40:18.188798 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:394:in `create_action'
E, [2020-03-23T14:40:18.188817 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2020-03-23T14:40:18.188865 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2020-03-23T14:40:18.188882 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2020-03-23T14:40:18.188897 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:380:in `each'
E, [2020-03-23T14:40:18.188913 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:380:in `transition_to'
E, [2020-03-23T14:40:18.188929 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:162:in `verify'
E, [2020-03-23T14:40:18.188945 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:191:in `block in test'
E, [2020-03-23T14:40:18.188960 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2020-03-23T14:40:18.190051 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:187:in `test'
E, [2020-03-23T14:40:18.190075 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/command.rb:198:in `public_send'
E, [2020-03-23T14:40:18.190097 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/command.rb:198:in `run_action_in_thread'
E, [2020-03-23T14:40:18.190113 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2020-03-23T14:40:18.190129 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2020-03-23T14:40:18.190145 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: ----End Backtrace-----
E, [2020-03-23T14:40:18.190161 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: ---Nested Exception---
E, [2020-03-23T14:40:18.190176 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: Class: Mixlib::ShellOut::ShellCommandFailed
E, [2020-03-23T14:40:18.190192 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: Message: Expected process to exit with [0], but received '100'
---- Begin output of docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20200323-4269-14oanc6 . ----
STDOUT: Sending build context to Docker daemon  986.1kB
Step 1/17 : FROM netmanagers/salt-2019.2-py3:ubuntu-18.04
 ---> 8b369f265be0
Step 2/17 : RUN [ ! -f "/sbin/initctl" ] || dpkg-divert --local --rename --add /sbin/initctl && ln -sf /bin/true /sbin/initctl
 ---> Using cache
 ---> d9831ce9b16b
Step 3/17 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 4f70242ef591
Step 4/17 : ENV container docker
 ---> Using cache
 ---> 54d68abaae2f
Step 5/17 : RUN apt-get update
 ---> Running in 4980e59b2d07
Get:1 https://repo.saltstack.com/py3/ubuntu/18.04/amd64/2019.2 bionic InRelease [2126 B]
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:3 https://repo.saltstack.com/py3/ubuntu/18.04/amd64/2019.2 bionic/main amd64 Packages [4398 B]
Get:4 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Reading package lists...
[91mE: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 10d 22h 56min 45s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 11d 0h 31min 42s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 10d 22h 59min 16s). Updates for this repository will not be applied.
[0m
STDERR: The command '/bin/sh -c apt-get update' returned a non-zero code: 100
---- End output of docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20200323-4269-14oanc6 . ----
Ran docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20200323-4269-14oanc6 . returned 100
E, [2020-03-23T14:40:18.190211 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: ----------------------
E, [2020-03-23T14:40:18.190228 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: ------Backtrace-------
E, [2020-03-23T14:40:18.190243 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/shell_out.rb:71:in `rescue in run_command'
E, [2020-03-23T14:40:18.190261 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/shell_out.rb:59:in `run_command'
E, [2020-03-23T14:40:18.190277 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/kitchen-docker-2.10.0/lib/kitchen/docker/helpers/cli_helper.rb:36:in `docker_command'
E, [2020-03-23T14:40:18.190293 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/kitchen-docker-2.10.0/lib/kitchen/docker/helpers/image_helper.rb:52:in `build_image'
E, [2020-03-23T14:40:18.190309 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/kitchen-docker-2.10.0/lib/kitchen/docker/container/linux.rb:38:in `create'
E, [2020-03-23T14:40:18.190325 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/kitchen-docker-2.10.0/lib/kitchen/driver/docker.rb:123:in `create'
E, [2020-03-23T14:40:18.190343 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:485:in `public_send'
E, [2020-03-23T14:40:18.190360 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:485:in `block in perform_action'
E, [2020-03-23T14:40:18.190375 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:552:in `synchronize_or_call'
E, [2020-03-23T14:40:18.190391 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:514:in `block in action'
E, [2020-03-23T14:40:18.190407 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2020-03-23T14:40:18.190423 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:513:in `action'
E, [2020-03-23T14:40:18.190438 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:485:in `perform_action'
E, [2020-03-23T14:40:18.190454 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:394:in `create_action'
E, [2020-03-23T14:40:18.190470 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2020-03-23T14:40:18.190488 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2020-03-23T14:40:18.190504 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2020-03-23T14:40:18.190520 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:380:in `each'
E, [2020-03-23T14:40:18.190536 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:380:in `transition_to'
E, [2020-03-23T14:40:18.190552 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:162:in `verify'
E, [2020-03-23T14:40:18.190568 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:191:in `block in test'
E, [2020-03-23T14:40:18.190584 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2020-03-23T14:40:18.190603 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/instance.rb:187:in `test'
E, [2020-03-23T14:40:18.190619 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/command.rb:198:in `public_send'
E, [2020-03-23T14:40:18.190635 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/command.rb:198:in `run_action_in_thread'
E, [2020-03-23T14:40:18.190654 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/test-kitchen-2.4.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2020-03-23T14:40:18.190670 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2020-03-23T14:40:18.190686 #4269] ERROR -- default-ubuntu-1804-2019-2-py3: ----End Backtrace-----
